Skip to content
ShivaniDubeyDev
stayrate-config-repo
Repository navigation
Code
Issues
Pull requests
Actions
Projects
Wiki
Security and quality
Insights
Settings
stayrate-config-repo
/
api-gateway.yml
in
main

Edit

Preview
Indent mode

Spaces
Indent size

2
Line wrap mode

No wrap
Editing api-gateway.yml file contents
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24
 25
 26
 27
 28
 29
 30
 31
 32
 33
 34
 35
 36
server:
  port: 8087

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-n6u7erw77d6ufb24.us.auth0.com/
      client:
        registration:
          auth0:
            client-id: aRJkQMhHWrxAJ3GI22mZtNnjbjnSJOuV
            client-secret: x9nQg3Sstf6DuSIrhEyxiUFGJt_jc0wijp1II9eDsEaHbKA3v6DQmwZMnS8P0QGM
            scope: openid, profile, email, offline_access
            provider: auth0
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8087/login/oauth2/code/auth0"
            # TO FORCE AUTH0 TO ISSUE A JWT ACCESS TOKEN
Use Control + Shift + m to toggle the tab key moving focus. Alternatively, use esc then tab to move to the next interactive element on the page.
 
